<a href="https://colab.research.google.com/github/parinitha672/Spend_DNA/blob/main/SPEND_DNA_PARINITHA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MINOR PROJECT **2**

In [1]:
#IMPORTING LINRARIES
import pandas as pd
import numpy as np

In [2]:
#loading the dataset
df=pd.read_csv("Data set for DADS June.csv")
#display first five records
df.head()

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,Debit,₹2462,678275.0,UPI,TXN190872
1,01-Jan-24,05:44,BHIM-BMTC,DR,50.00,681007.0,UPI,TXN143064
2,01-Jan-24,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,CR,₹84728,484728.0,NEFT,TXN246316
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,Debit,₹1828,-748745.0,UPI,TXN569226
4,01 Jan 2024,14:23,BHIM-BLINKIT,Debit,270.00,680737.0,UPI,TXN968962

In [3]:
#check the shape of the dataset
print("Rows :",df.shape[0])
print("columns :",df.shape[1])

Rows : 1328
columns : 8

In [4]:
#display column name
print(df.columns)

Index(['Date', 'Time', 'Description', 'Type', 'Amount', 'Balance', 'Mode',
       'Ref'],
      dtype='object')

In [5]:
#check information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1328 entries, 0 to 1327
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         1328 non-null   object
 1   Time         1328 non-null   object
 2   Description  1328 non-null   object
 3   Type         1328 non-null   object
 4   Amount       1328 non-null   object
 5   Balance      1328 non-null   float64
 6   Mode         1328 non-null   object
 7   Ref          1328 non-null   object
dtypes: float64(1), object(7)
memory usage: 83.1+ KB

In [6]:
#display summary statistics
df.describe(include="all")

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
count,1328,1328,1328,1328,1328,1328.000000,1328,1328
unique,617,832,283,3,1141,NaN,4,1307
top,2024-02-07,16:19,POS SWIGGY BANGALORE,DR,"Rs. 15,000",NaN,UPI,TXN427270
freq,6,6,30,670,5,NaN,1299,2
mean,NaN,NaN,NaN,NaN,NaN,147805.330572,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,341059.809969,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,-769127.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,-104585.750000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,151650.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,448324.250000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,720079.000000,NaN,NaN

In [7]:
#check missing values
missing_values=df.isnull().sum()
missing_values

Date           0
Time           0
Description    0
Type           0
Amount         0
Balance        0
Mode           0
Ref            0
dtype: int64

In [8]:
#check duplicate values
duplicate_records=df.duplicated().sum()
print("Duplicated Records :", duplicate_records)

Duplicated Records : 18

In [9]:
#remove duplicated records
df=df.drop_duplicates()
print("Remaining Records :",len(df))

Remaining Records : 1310

In [10]:
# Convert Date column into datetime format
df["Date"] = pd.to_datetime(
    df["Date"],
    dayfirst=True,
    errors="coerce"
)
df["Date"].head()

0   2024-01-01
1          NaT
2          NaT
3   2024-01-01
4          NaT
Name: Date, dtype: datetime64[ns]

In [11]:
# Clean Amount column
df["Amount"] = df["Amount"].astype(str)
df["Amount"] = df["Amount"].str.replace("₹", "")
df["Amount"] = df["Amount"].str.replace("Rs.", "")
df["Amount"] = df["Amount"].str.replace(",", "")
df["Amount"] = df["Amount"].str.strip()
df["Amount"] = pd.to_numeric(
    df["Amount"],
    errors="coerce"
)
df["Amount"].head()

0     2462.0
1       50.0
2    84728.0
3     1828.0
4      270.0
Name: Amount, dtype: float64

In [12]:
# Standardize transaction type
df["Type"] = df["Type"].str.lower()
df["Type"] = df["Type"].replace("dr", "debit")
df["Type"] = df["Type"].replace("cr", "credit")
df["Type"].value_counts()

Type
debit     1304
credit       6
Name: count, dtype: int64

In [13]:
# Check missing values after cleaning
print(df.isnull().sum())

Date           1167
Time              0
Description       0
Type              0
Amount            0
Balance           0
Mode              0
Ref               0
dtype: int64

In [14]:
# Remove rows with invalid dates or amounts
df = df.dropna(subset=["Date", "Amount"])
print("Clean Dataset Shape :", df.shape)

Clean Dataset Shape : (143, 8)

In [15]:
# Display cleaned dataset
df.head()

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,debit,2462.0,678275.0,UPI,TXN190872
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,debit,1828.0,-748745.0,UPI,TXN569226
5,2024-01-01,14:48,BHIM ZEPTO,debit,625.0,677650.0,UPI,TXN370902
6,2024-01-01,14:50,UPI-UBER-2426@HDFCBANK,debit,148.0,677020.0,UPI,TXN546173
8,2024-02-01,05:18,POS SWIGGY BANGALORE,debit,537.0,676177.0,UPI,TXN293319

In [16]:
# Check unique transaction descriptions
print("Total Unique Descriptions :", df["Description"].nunique())
df["Description"].unique()

Total Unique Descriptions : 81

array(['AMAZON SELLER SVCS', 'UPI-AMAN-8934@OKAXIS', 'BHIM ZEPTO',
       'UPI-UBER-2426@HDFCBANK', 'POS SWIGGY BANGALORE',
       'ANI Technologies', 'POS SWIGGY-RESTAURANT', 'POS UBER BANGALORE',
       'TWC INDIA', 'UPI-STARBUCKS@AXIS', 'POS BLINKIT',
       'ZOMATO MEDIA P L', 'BHIM SWIGGY', 'OLA CABS', 'UPI-DMART@OKAXIS',
       'POS ZEPTO BANGALORE', 'UPI-MYNTRA@HDFCBANK',
       'BANGALORE ELEC SUPPLY', 'Amazon Pay India',
       'UPI-PRIYA-2221@OKAXIS', 'INSTAMART BANGALORE',
       'UPI-ZOMATO-LIMITED@PAYTM', 'UPI-SWIGGY-7959@HDFCBANK',
       'UPI-SWIGGY-INSTAMART@OKAXIS', 'POS OLA-PRIME',
       'POS EMPIRE RESTAURANT', 'SWIGGY-INSTAMART', 'POS NYKAA BANGALORE',
       'ROPPEN TRANSPORTATION', 'UPI-NYKAA@AXIS', 'UPI-SWIGGY4619@OKAXIS',
       'UPI-FLIPKART@HDFCBANK', 'IMPS ZERODHA-COIN',
       'UPI-THIRDWAVE@OKAXIS', 'UPI-SWIGGY-1309@HDFCBANK',
       'NEFT-TECHCRUSH LABS-SALARY MAY24', 'BHIM-BLINKIT',
       'UPI-ZEPTO-4547@HDFCBANK', 'RAPIDO BIKE TAXI',
       'UPI-RESTAURANT-6377@PAYTM', 'Swiggy*Order', 'COFFEE DAY GLOBAL',
       'FLIPKART INDIA', 'UPI-CCD@HDFCBANK', 'UPI-VIKAS-5416@OKAXIS',
       'UPI-BOOKMYSHOW@HDFCBANK', 'UPI-HOTSTAR@AXIS',
       'UPI-ZOMATO6436@OKICICI', 'NETFLIX.COM', 'BMS MOVIE TICKETS',
       'UPI-RESTAURANT-4630@PAYTM', 'INNOVATIVE RETAIL',
       'POS THIRD WAVE COFFEE', 'AVENUE SUPERMARTS', 'ZOMATO-DINING',
       'AMZN-INTPYMT', 'UPI-SWIGGY9600@OKAXIS',
       'UPI-SWIGGY-3513@HDFCBANK', 'UPI-BIGBASKET@HDFCBANK',
       'POS HP PETROL STATION', 'OLA ELECTRIC', 'KIRANAKART TECH',
       'POS BANGALORE RESTAURANT', 'IMPS-RENT-LANDLORD-49966195',
       'UPI-SWIGGY8720@OKAXIS', 'UPI-SWIGGY9756@OKAXIS',
       'BUNDL TECH-INSTAMART', 'POS INSTAMART', 'ATM-WDL-SBI-0279',
       'UPI-RAPIDO@OKAXIS', 'ZOMATO BENGALURU', 'Uber*Trip',
       'IMPS-RENT-LANDLORD-35126704', 'UPI-GROWWPAY@HDFCBANK',
       'UPI-ANKIT-6092@OKAXIS', 'UPI-VI-RECHARGE@HDFCBANK',
       'UPI-SWIGGY7538@OKAXIS', 'POS STARBUCKS BANGALORE',
       'ATM-WDL-SBI-4084', 'ATM-WDL-ICICI-4739', 'POS ZOMATO'],
      dtype=object)

In [17]:
# Display first 30 unique descriptions
description_list = df["Description"].unique()
for i in range(30):
    print(description_list[i])

AMAZON SELLER SVCS
UPI-AMAN-8934@OKAXIS
BHIM ZEPTO
UPI-UBER-2426@HDFCBANK
POS SWIGGY BANGALORE
ANI Technologies
POS SWIGGY-RESTAURANT
POS UBER BANGALORE
TWC INDIA
UPI-STARBUCKS@AXIS
POS BLINKIT
ZOMATO MEDIA P L
BHIM SWIGGY
OLA CABS
UPI-DMART@OKAXIS
POS ZEPTO BANGALORE
UPI-MYNTRA@HDFCBANK
BANGALORE ELEC SUPPLY
Amazon Pay India
UPI-PRIYA-2221@OKAXIS
INSTAMART BANGALORE
UPI-ZOMATO-LIMITED@PAYTM
UPI-SWIGGY-7959@HDFCBANK
UPI-SWIGGY-INSTAMART@OKAXIS
POS OLA-PRIME
POS EMPIRE RESTAURANT
SWIGGY-INSTAMART
POS NYKAA BANGALORE
ROPPEN TRANSPORTATION
UPI-NYKAA@AXIS

In [18]:
# Create vendor dictionary
vendor_dict = {
    "Swiggy": ["SWIGGY", "BUNDL"],
    "Zomato": ["ZOMATO"],
    "Zepto": ["ZEPTO"],
    "Blinkit": ["BLINKIT"],
    "Instamart": ["INSTAMART"],
    "Amazon": ["AMAZON", "AMZN"],
    "Flipkart": ["FLIPKART"],
    "Myntra": ["MYNTRA"],
    "Nykaa": ["NYKAA"],
    "Ajio": ["AJIO"],
    "BigBasket": ["BIGBASKET"],
    "DMart": ["DMART", "AVENUE SUPERMARTS"],
    "Uber": ["UBER", "ANI TECHNOLOGIES"],
    "Ola": ["OLA"],
    "Rapido": ["RAPPEN", "ROPPEN"],
    "BookMyShow": ["BOOKMYSHOW", "BMS"],
    "Starbucks": ["STARBUCKS"],
    "Third Wave Coffee": ["THIRDWAVE", "THIRD WAVE"],
    "Cafe Coffee Day": ["CCD", "COFFEE DAY"],
    "Empire Restaurant": ["EMPIRE"],
    "Bangalore Restaurant": ["BANGALORE RESTAURANT"],
    "HP Petrol": ["HP PETROL"],
    "Netflix": ["NETFLIX"],
    "Spotify": ["SPOTIFY"],
    "Prime Video": ["PRIME"],
    "Hotstar": ["HOTSTAR"],
    "Zerodha": ["ZERODHA"],
    "Groww": ["GROWW"],
    "Paytm": ["PAYTM"],
    "VI": ["VI RECHARGE", "VI-RECHARGE"],
    "Jio": ["JIO"],
    "Electricity": ["ELEC", "BESCOM"],
    "Salary": ["SALARY"],
    "Rent": ["LANDLORD", "RENT"],
    "Personal Transfer": [
        "UPI-AMAN",
        "UPI-PRIYA",
        "UPI-VIKAS",
        "UPI-ANKIT"
    ],
    "ATM Withdrawal": ["ATM"]
}

In [19]:
# Function to identify vendors
def find_vendor(text):
    text = str(text).upper()
    for vendor in vendor_dict:
        for word in vendor_dict[vendor]:
            if word in text:
                return vendor
    return "Uncategorised"

In [20]:
df["Vendor"] = df["Description"].apply(find_vendor)
uncategorised = df[df["Vendor"] == "Uncategorised"]
print("Remaining Uncategorised :", len(uncategorised))
uncategorised["Description"].drop_duplicates()

Remaining Uncategorised : 8

25             TWC INDIA
453     RAPIDO BIKE TAXI
515    INNOVATIVE RETAIL
901      KIRANAKART TECH
955    UPI-RAPIDO@OKAXIS
Name: Description, dtype: object

In [21]:
# Apply vendor extraction
df["Vendor"] = df["Description"].apply(find_vendor)
df[["Description", "Vendor"]].head(15)

               Description             Vendor
0       AMAZON SELLER SVCS             Amazon
3     UPI-AMAN-8934@OKAXIS  Personal Transfer
5               BHIM ZEPTO              Zepto
6   UPI-UBER-2426@HDFCBANK               Uber
8     POS SWIGGY BANGALORE             Swiggy
16        ANI Technologies               Uber
20   POS SWIGGY-RESTAURANT             Swiggy
22      POS UBER BANGALORE               Uber
23   POS SWIGGY-RESTAURANT             Swiggy
25               TWC INDIA      Uncategorised
29      UPI-STARBUCKS@AXIS          Starbucks
33             POS BLINKIT            Blinkit
35        ZOMATO MEDIA P L             Zomato
51             BHIM SWIGGY             Swiggy
54                OLA CABS                Ola

In [22]:
# Count vendors
print("Total Vendors :", df["Vendor"].nunique())
df["Vendor"].value_counts()

Total Vendors : 33

Vendor
Swiggy                  28
Zomato                  16
Uber                    12
Ola                      8
Uncategorised            8
Zepto                    5
Nykaa                    4
Starbucks                4
Personal Transfer        4
Zerodha                  4
DMart                    4
Empire Restaurant        4
Flipkart                 4
BookMyShow               4
Amazon                   3
Cafe Coffee Day          3
Instamart                3
ATM Withdrawal           3
Electricity              2
Myntra                   2
Blinkit                  2
Rent                     2
Salary                   2
Paytm                    2
Third Wave Coffee        2
Rapido                   1
Hotstar                  1
Netflix                  1
BigBasket                1
Bangalore Restaurant     1
HP Petrol                1
Groww                    1
VI                       1
Name: count, dtype: int64

In [23]:
# Check uncategorised descriptions
uncategorised = df[df["Vendor"] == "Uncategorised"]
print("Uncategorised Transactions :", len(uncategorised))
uncategorised["Description"].drop_duplicates()

Uncategorised Transactions : 8

25             TWC INDIA
453     RAPIDO BIKE TAXI
515    INNOVATIVE RETAIL
901      KIRANAKART TECH
955    UPI-RAPIDO@OKAXIS
Name: Description, dtype: object

In [24]:
# Create category dictionary
category_dict = {
    "Swiggy": "Food Delivery",
    "Zomato": "Food Delivery",
    "Zepto": "Quick Commerce",
    "Blinkit": "Quick Commerce",
    "Instamart": "Quick Commerce",
    "Amazon": "E-commerce",
    "Flipkart": "E-commerce",
    "Myntra": "E-commerce",
    "Nykaa": "E-commerce",
    "Ajio": "E-commerce",
    "DMart": "Groceries",
    "BigBasket": "Groceries",
    "Uber": "Transport",
    "Ola": "Transport",
    "Rapido": "Transport",
    "Starbucks": "Cafe",
    "Cafe Coffee Day": "Cafe",
    "Third Wave Coffee": "Cafe",
    "Empire Restaurant": "Restaurants",
    "Bangalore Restaurant": "Restaurants",
    "Netflix": "Subscriptions",
    "Spotify": "Subscriptions",
    "Prime Video": "Subscriptions",
    "Hotstar": "Subscriptions",
    "Electricity": "Utilities",
    "HP Petrol": "Fuel",
    "BookMyShow": "Entertainment",
    "Zerodha": "Investments",
    "Groww": "Investments",
    "Salary": "Income",
    "Rent": "Rent",
    "Personal Transfer": "Personal Transfer",
    "ATM Withdrawal": "Cash Withdrawal",
    "Paytm": "Wallet",
    "JiIo": "Recharge",
    "V": "Recharge"
}

In [25]:
# Assign categories
df["Category"] = df["Vendor"].map(category_dict)
df[["Vendor", "Category"]].head(10)

               Vendor           Category
0              Amazon         E-commerce
3   Personal Transfer  Personal Transfer
5               Zepto     Quick Commerce
6                Uber          Transport
8              Swiggy      Food Delivery
16               Uber          Transport
20             Swiggy      Food Delivery
22               Uber          Transport
23             Swiggy      Food Delivery
25      Uncategorised                NaN

In [26]:
# Fill missing categories
df["Category"] = df["Category"].fillna("Others")
print("Category assignment completed.")

Category assignment completed.

In [27]:
# Count transactions in each category
df["Category"].value_counts()

Category
Food Delivery        44
Transport            21
E-commerce           13
Quick Commerce       10
Cafe                  9
Others                9
Restaurants           5
Groceries             5
Investments           5
Personal Transfer     4
Entertainment         4
Cash Withdrawal       3
Utilities             2
Income                2
Wallet                2
Subscriptions         2
Rent                  2
Fuel                  1
Name: count, dtype: int64

In [28]:
# Check unique categories
print("Total Categories :", df["Category"].nunique())
print(df["Category"].unique())

Total Categories : 18
['E-commerce' 'Personal Transfer' 'Quick Commerce' 'Transport'
 'Food Delivery' 'Others' 'Cafe' 'Groceries' 'Utilities' 'Restaurants'
 'Investments' 'Income' 'Wallet' 'Entertainment' 'Subscriptions' 'Fuel'
 'Rent' 'Cash Withdrawal']

In [29]:
# Verify vendor-category mapping
df[["Vendor", "Category"]].drop_duplicates().sort_values("Category")

                    Vendor           Category
274      Third Wave Coffee               Cafe
29               Starbucks               Cafe
461        Cafe Coffee Day               Cafe
952         ATM Withdrawal    Cash Withdrawal
0                   Amazon         E-commerce
267               Flipkart         E-commerce
70                  Myntra         E-commerce
260                  Nykaa         E-commerce
485             BookMyShow      Entertainment
35                  Zomato      Food Delivery
8                   Swiggy      Food Delivery
747              HP Petrol               Fuel
58                   DMart          Groceries
746              BigBasket          Groceries
438                 Salary             Income
272                Zerodha        Investments
1159                 Groww        Investments
1178                    VI             Others
25           Uncategorised             Others
3        Personal Transfer  Personal Transfer
223              Instamart     Quick Commerce
33                 Blinkit     Quick Commerce
5                    Zepto     Quick Commerce
913                   Rent               Rent
903   Bangalore Restaurant        Restaurants
252      Empire Restaurant        Restaurants
488                Hotstar      Subscriptions
501                Netflix      Subscriptions
54                     Ola          Transport
6                     Uber          Transport
261                 Rapido          Transport
85             Electricity          Utilities
457                  Paytm             Wallet

In [30]:
# Separate credit and debit transactions
credit_data = df[df["Type"] == "credit"]
debit_data = df[df["Type"] == "debit"]
print("Credit Transactions :", len(credit_data))
print("Debit Transactions :", len(debit_data))

Credit Transactions : 2
Debit Transactions : 141

In [31]:
# Calculate total credits and total debits
total_credit = credit_data["Amount"].sum()
total_debit = debit_data["Amount"].sum()
print("Total Credit :", total_credit)
print("Total Debit :", total_debit)

Total Credit : 170094.0
Total Debit : 205310.0

In [32]:
# Calculate net savings
net_savings = total_credit - total_debit
print("Net Savings :", net_savings)

Net Savings : -35216.0

In [33]:
# Calculate savings rate
savings_rate = (net_savings / total_credit) * 100
print("Savings Rate :", round(savings_rate, 2), "%")

Savings Rate : -20.7 %

In [34]:
# Calculate total number of transactions
total_transactions = len(df)
print("Total Transactions :", total_transactions)

Total Transactions : 143

In [35]:
# Find top 5 spending categories
top_categories = (
    debit_data.groupby("Category")["Amount"]
    .sum()
    .sort_values(ascending=False)
    .head(5)
)
top_categories

Category
Investments      64496.0
E-commerce       36416.0
Rent             36000.0
Food Delivery    19617.0
Groceries         7672.0
Name: Amount, dtype: float64

In [36]:
# Find top 5 vendors
top_vendors = (
    debit_data.groupby("Vendor")["Amount"]
    .sum()
    .sort_values(ascending=False)
    .head(5)
)
top_vendors

Vendor
Zerodha     60000.0
Rent        36000.0
Myntra      13629.0
Swiggy      12638.0
Flipkart    10041.0
Name: Amount, dtype: float64

In [37]:
# Count transactions for each vendor
vendor_count = (
    debit_data.groupby("Vendor")["Amount"]
    .count()
    .sort_values(ascending=False)
)
vendor_count.head(10)

Vendor
Swiggy           28
Zomato           16
Uber             12
Ola               8
Uncategorised     8
Zepto             5
DMart             4
BookMyShow        4
Nykaa             4
Starbucks         4
Name: Amount, dtype: int64

In [38]:
# Display executive summary
print("=" * 50)
print("SPENDING OVERVIEW")
print("=" * 50)
print("Total Credit       :", round(total_credit, 2))
print("Total Debit        :", round(total_debit, 2))
print("Net Savings        :", round(net_savings, 2))
print("Savings Rate       :", round(savings_rate, 2), "%")
print("Transactions       :", total_transactions)
print("Unique Vendors     :", df["Vendor"].nunique())
print("=" * 50)

==================================================
SPENDING OVERVIEW
==================================================
Total Credit       : 170094.0
Total Debit        : 205310.0
Net Savings        : -35216.0
Savings Rate       : -20.7 %
Transactions       : 143
Unique Vendors     : 33
==================================================

In [39]:
# Display top spending categories
print("Top 5 Spending Categories")
print(top_categories)

Top 5 Spending Categories
Category
Investments      64496.0
E-commerce       36416.0
Rent             36000.0
Food Delivery    19617.0
Groceries         7672.0
Name: Amount, dtype: float64

In [40]:
# Display top vendors
print("Top 5 Vendors")
print(top_vendors)

Top 5 Vendors
Vendor
Zerodha     60000.0
Rent        36000.0
Myntra      13629.0
Swiggy      12638.0
Flipkart    10041.0
Name: Amount, dtype: float64

In [41]:
# Extract month from Date column
df["Month"] = df["Date"].dt.month
df[["Date", "Month"]].head()

        Date  Month
0 2024-01-01      1
3 2024-01-01      1
5 2024-01-01      1
6 2024-01-01      1
8 2024-02-01      2

In [42]:
# Display transaction count for each month
monthly_transactions = df["Month"].value_counts().sort_index()
monthly_transactions

Month
1     18
2     14
3     13
4      6
5      8
6     10
7     15
8     13
9     10
10     9
11    12
12    15
Name: count, dtype: int64

In [43]:
# Update debit and credit data after adding Month column
credit_data = df[df["Type"] == "credit"]
debit_data = df[df["Type"] == "debit"]

In [44]:
#calculate monthly spending
monthly_spending = (
    debit_data.copy()
    .assign(Month=debit_data["Date"].dt.month)
    .groupby("Month")["Amount"]
    .sum()
    .sort_index()
)
monthly_spending

Month
1     14972.0
2      6390.0
3     26578.0
4      5246.0
5     21011.0
6      9292.0
7     23632.0
8     41383.0
9     14154.0
10     5541.0
11     6366.0
12    30745.0
Name: Amount, dtype: float64

In [45]:
# Create category-wise monthly spending table
monthly_category = pd.pivot_table(
    debit_data.copy().assign(Month=debit_data["Date"].dt.month),
    values="Amount",
    index="Category",
    columns="Month",
    aggfunc="sum",
    fill_value=0
)
monthly_category

Month,1,2,3,4,5,6,7,8,9,10,11,12
Category,,,,,,,,,,,,
Cafe,295.0,355.0,0.0,688.0,166.0,0.0,0.0,591.0,0.0,0.0,809.0,0.0
Cash Withdrawal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2500.0,500.0
E-commerce,6972.0,996.0,2147.0,3311.0,0.0,4868.0,2425.0,860.0,10745.0,0.0,0.0,4092.0
Entertainment,0.0,0.0,0.0,343.0,0.0,0.0,562.0,0.0,0.0,1455.0,0.0,0.0
Food Delivery,1180.0,3454.0,2862.0,632.0,1159.0,1636.0,1686.0,1446.0,712.0,183.0,1909.0,2758.0
Fuel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1087.0
Groceries,0.0,0.0,1213.0,0.0,0.0,0.0,1257.0,1862.0,0.0,0.0,0.0,3340.0
Investments,0.0,0.0,0.0,0.0,0.0,0.0,15000.0,34496.0,0.0,0.0,0.0,15000.0
Others,0.0,81.0,169.0,272.0,0.0,794.0,0.0,0.0,0.0,728.0,801.0,373.0
Personal Transfer,1828.0,0.0,0.0,0.0,0.0,1860.0,0.0,0.0,246.0,0.0,0.0,1266.0
Quick Commerce,1616.0,697.0,0.0,0.0,502.0,0.0,510.0,0.0,1110.0,0.0,347.0,0.0
Rent,0.0,0.0,18000.0,0.0,18000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Restaurants,1794.0,0.0,1247.0,0.0,753.0,0.0,308.0,1480.0,0.0,0.0,0.0,0.0
Subscriptions,0.0,0.0,0.0,0.0,0.0,0.0,1473.0,0.0,210.0,0.0,0.0,0.0
Transport,1287.0,807.0,439.0,0.0,431.0,134.0,411.0,648.0,1131.0,1232.0,0.0,0.0
Utilities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1344.0,0.0,2329.0
Wallet,0.0,0.0,501.0,0.0,0.0,0.0,0.0,0.0,0.0,599.0,0.0,0.0

In [46]:
# Display category-wise monthly spending
print(monthly_category)

Month                  1       2        3       4        5       6        7   \
Category
Cafe                295.0   355.0      0.0   688.0    166.0     0.0      0.0
Cash Withdrawal       0.0     0.0      0.0     0.0      0.0     0.0      0.0
E-commerce         6972.0   996.0   2147.0  3311.0      0.0  4868.0   2425.0
Entertainment         0.0     0.0      0.0   343.0      0.0     0.0    562.0
Food Delivery      1180.0  3454.0   2862.0   632.0   1159.0  1636.0   1686.0
Fuel                  0.0     0.0      0.0     0.0      0.0     0.0      0.0
Groceries             0.0     0.0   1213.0     0.0      0.0     0.0   1257.0
Investments           0.0     0.0      0.0     0.0      0.0     0.0  15000.0
Others                0.0    81.0    169.0   272.0      0.0   794.0      0.0
Personal Transfer  1828.0     0.0      0.0     0.0      0.0  1860.0      0.0
Quick Commerce     1616.0   697.0      0.0     0.0    502.0     0.0    510.0
Rent                  0.0     0.0  18000.0     0.0  18000.0     0.0      0.0
Restaurants        1794.0     0.0   1247.0     0.0    753.0     0.0    308.0
Subscriptions         0.0     0.0      0.0     0.0      0.0     0.0   1473.0
Transport          1287.0   807.0    439.0     0.0    431.0   134.0    411.0
Utilities             0.0     0.0      0.0     0.0      0.0     0.0      0.0
Wallet                0.0     0.0    501.0     0.0      0.0     0.0      0.0

Month                   8        9       10      11       12
Category
Cafe                 591.0      0.0     0.0   809.0      0.0
Cash Withdrawal        0.0      0.0     0.0  2500.0    500.0
E-commerce           860.0  10745.0     0.0     0.0   4092.0
Entertainment          0.0      0.0  1455.0     0.0      0.0
Food Delivery       1446.0    712.0   183.0  1909.0   2758.0
Fuel                   0.0      0.0     0.0     0.0   1087.0
Groceries           1862.0      0.0     0.0     0.0   3340.0
Investments        34496.0      0.0     0.0     0.0  15000.0
Others                 0.0      0.0   728.0   801.0    373.0
Personal Transfer      0.0    246.0     0.0     0.0   1266.0
Quick Commerce         0.0   1110.0     0.0   347.0      0.0
Rent                   0.0      0.0     0.0     0.0      0.0
Restaurants         1480.0      0.0     0.0     0.0      0.0
Subscriptions          0.0    210.0     0.0     0.0      0.0
Transport            648.0   1131.0  1232.0     0.0      0.0
Utilities              0.0      0.0  1344.0     0.0   2329.0
Wallet                 0.0      0.0   599.0     0.0      0.0

In [47]:
# Calculate increase in spending from first month to last month
growth = {}
for category in monthly_category.index:
    first_month = monthly_category.loc[category].iloc[0]
    last_month = monthly_category.loc[category].iloc[-1]
    difference = last_month - first_month
    growth[category] = difference
growth

{'Cafe': np.float64(-295.0),
 'Cash Withdrawal': np.float64(500.0),
 'E-commerce': np.float64(-2880.0),
 'Entertainment': np.float64(0.0),
 'Food Delivery': np.float64(1578.0),
 'Fuel': np.float64(1087.0),
 'Groceries': np.float64(3340.0),
 'Investments': np.float64(15000.0),
 'Others': np.float64(373.0),
 'Personal Transfer': np.float64(-562.0),
 'Quick Commerce': np.float64(-1616.0),
 'Rent': np.float64(0.0),
 'Restaurants': np.float64(-1794.0),
 'Subscriptions': np.float64(0.0),
 'Transport': np.float64(-1287.0),
 'Utilities': np.float64(2329.0),
 'Wallet': np.float64(0.0)}

In [48]:
# Find category with highest increase
highest_growth = max(growth, key=growth.get)
print("Highest Increase in Spending")
print(highest_growth)
print(growth[highest_growth])

Highest Increase in Spending
Investments
15000.0

In [49]:
# Find category with highest decrease
lowest_growth = min(growth, key=growth.get)
print("Highest Decrease in Spending")
print(lowest_growth)
print(growth[lowest_growth])

Highest Decrease in Spending
E-commerce
-2880.0

In [50]:
# Monthly spending summary
print("=" * 50)
print("MONTHLY SPENDING")
print("=" * 50)
for month in monthly_spending.index:
    print(
        "Month",
        month,
        ":",
        round(monthly_spending[month], 2)
    )

==================================================
MONTHLY SPENDING
==================================================
Month 1 : 14972.0
Month 2 : 6390.0
Month 3 : 26578.0
Month 4 : 5246.0
Month 5 : 21011.0
Month 6 : 9292.0
Month 7 : 23632.0
Month 8 : 41383.0
Month 9 : 14154.0
Month 10 : 5541.0
Month 11 : 6366.0
Month 12 : 30745.0

In [51]:
# Display category-wise monthly spending
monthly_category

Month,1,2,3,4,5,6,7,8,9,10,11,12
Category,,,,,,,,,,,,
Cafe,295.0,355.0,0.0,688.0,166.0,0.0,0.0,591.0,0.0,0.0,809.0,0.0
Cash Withdrawal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2500.0,500.0
E-commerce,6972.0,996.0,2147.0,3311.0,0.0,4868.0,2425.0,860.0,10745.0,0.0,0.0,4092.0
Entertainment,0.0,0.0,0.0,343.0,0.0,0.0,562.0,0.0,0.0,1455.0,0.0,0.0
Food Delivery,1180.0,3454.0,2862.0,632.0,1159.0,1636.0,1686.0,1446.0,712.0,183.0,1909.0,2758.0
Fuel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1087.0
Groceries,0.0,0.0,1213.0,0.0,0.0,0.0,1257.0,1862.0,0.0,0.0,0.0,3340.0
Investments,0.0,0.0,0.0,0.0,0.0,0.0,15000.0,34496.0,0.0,0.0,0.0,15000.0
Others,0.0,81.0,169.0,272.0,0.0,794.0,0.0,0.0,0.0,728.0,801.0,373.0
Personal Transfer,1828.0,0.0,0.0,0.0,0.0,1860.0,0.0,0.0,246.0,0.0,0.0,1266.0
Quick Commerce,1616.0,697.0,0.0,0.0,502.0,0.0,510.0,0.0,1110.0,0.0,347.0,0.0
Rent,0.0,0.0,18000.0,0.0,18000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Restaurants,1794.0,0.0,1247.0,0.0,753.0,0.0,308.0,1480.0,0.0,0.0,0.0,0.0
Subscriptions,0.0,0.0,0.0,0.0,0.0,0.0,1473.0,0.0,210.0,0.0,0.0,0.0
Transport,1287.0,807.0,439.0,0.0,431.0,134.0,411.0,648.0,1131.0,1232.0,0.0,0.0
Utilities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1344.0,0.0,2329.0
Wallet,0.0,0.0,501.0,0.0,0.0,0.0,0.0,0.0,0.0,599.0,0.0,0.0

In [52]:
# Extract hour from Time column
df["Hour"] = df["Time"].str[:2].astype(int)
df[["Time", "Hour"]].head()

    Time  Hour
0  03:11     3
3  14:07    14
5  14:48    14
6  14:50    14
8  05:18     5

In [53]:
# Update debit transactions
debit_data = df[df["Type"] == "debit"]
print("Debit Transactions :", len(debit_data))

Debit Transactions : 141

In [54]:
# Count transactions by hour
hourly_transactions = debit_data.groupby("Hour")["Amount"].count()
hourly_transactions

Hour
0      5
1      2
2      2
3      2
4      2
5      3
6      2
7      3
8      4
9      6
10    11
11     8
12     9
13     9
14    10
15     7
16     6
17     7
18    13
19     4
20     9
21     9
22     5
23     3
Name: Amount, dtype: int64

In [55]:
# Calculate spending by hour
hourly_spending = debit_data.groupby("Hour")["Amount"].sum()
hourly_spending

Hour
0      1820.0
1      1462.0
2      1015.0
3      3228.0
4     15413.0
5      5458.0
6      1948.0
7      1668.0
8      3542.0
9      2678.0
10    49574.0
11     8739.0
12     3729.0
13    22872.0
14    23670.0
15     3765.0
16     2753.0
17     3200.0
18    14213.0
19     5950.0
20    16097.0
21     7361.0
22     3728.0
23     1427.0
Name: Amount, dtype: float64

In [56]:
# Calculate category-wise hourly spending
hourly_category = pd.pivot_table(
    debit_data,
    values="Amount",
    index="Category",
    columns="Hour",
    aggfunc="sum",
    fill_value=0
)
hourly_category

Hour,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
Category,,,,,,,,,,,,,,,,,,,,,
Cafe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,241.0,376.0,...,166.0,0.0,447.0,295.0,0.0,0.0,0.0,0.0,0.0,0.0
Cash Withdrawal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,500.0,...,500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
E-commerce,0.0,842.0,0.0,2462.0,0.0,0.0,1626.0,860.0,0.0,0.0,...,0.0,1583.0,0.0,0.0,6899.0,4092.0,10745.0,3311.0,0.0,0.0
Entertainment,562.0,620.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,835.0,0.0,0.0,0.0,0.0,0.0,343.0,0.0
Food Delivery,394.0,0.0,318.0,0.0,413.0,537.0,0.0,0.0,369.0,383.0,...,368.0,1274.0,377.0,919.0,1517.0,771.0,1477.0,2078.0,1525.0,844.0
Fuel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1087.0,0.0,0.0,0.0,0.0
Groceries,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2430.0,0.0,...,0.0,0.0,0.0,0.0,910.0,0.0,1257.0,0.0,0.0,0.0
Investments,0.0,0.0,0.0,0.0,15000.0,4496.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Others,373.0,0.0,0.0,766.0,0.0,0.0,0.0,0.0,0.0,272.0,...,35.0,0.0,352.0,442.0,169.0,0.0,0.0,81.0,0.0,0.0
Personal Transfer,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1828.0,0.0,246.0,0.0,0.0,0.0,0.0,1266.0,1860.0,0.0
Quick Commerce,0.0,0.0,697.0,0.0,0.0,0.0,0.0,0.0,502.0,791.0,...,1152.0,0.0,0.0,200.0,543.0,0.0,0.0,0.0,0.0,583.0
Rent,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,18000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Restaurants,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1480.0,0.0,2000.0,0.0,0.0,0.0
Subscriptions,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1473.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Transport,491.0,0.0,0.0,0.0,0.0,425.0,322.0,808.0,0.0,356.0,...,148.0,908.0,496.0,0.0,366.0,0.0,618.0,625.0,0.0,0.0
Utilities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1344.0,2329.0,0.0,0.0,0.0,0.0,0.0
Wallet,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [57]:
# Find busiest spending hour
busy_hour = hourly_transactions.idxmax()
print("Most Active Spending Hour :", busy_hour)
print("Transactions :", hourly_transactions.max())

Most Active Spending Hour : 18
Transactions : 13

In [58]:
# Food Delivery transactions
food_data = debit_data[
    debit_data["Category"] == "Food Delivery"
]
food_hour = food_data.groupby("Hour")["Amount"].count()
food_hour

Hour
0     1
2     1
4     1
5     1
8     1
9     1
11    4
12    7
13    2
14    1
15    3
16    1
17    3
18    3
19    2
20    3
21    4
22    3
23    2
Name: Amount, dtype: int64

In [59]:
# Find peak food delivery hour
peak_food_hour = food_hour.idxmax()
print("Peak Food Delivery Hour :", peak_food_hour)
print("Orders :", food_hour.max())

Peak Food Delivery Hour : 12
Orders : 7

In [60]:
# Cafe transactions
cafe_data = debit_data[
    debit_data["Category"] == "Cafe"
]
cafe_hour = cafe_data.groupby("Hour")["Amount"].count()
cafe_hour

Hour
8     1
9     1
10    4
14    1
16    1
17    1
Name: Amount, dtype: int64

In [61]:
# Peak cafe hour
peak_cafe_hour = cafe_hour.idxmax()
print("Peak Cafe Hour :", peak_cafe_hour)
print("Transactions :", cafe_hour.max())

Peak Cafe Hour : 10
Transactions : 4

In [62]:
# Display hourly summary
print("=" * 50)
print("TIME OF DAY ANALYSIS")
print("=" * 50)
print("Most Active Hour :", busy_hour)
print("Peak Food Delivery Hour :", peak_food_hour)
print("Peak Cafe Hour :", peak_cafe_hour)

==================================================
TIME OF DAY ANALYSIS
==================================================
Most Active Hour : 18
Peak Food Delivery Hour : 12
Peak Cafe Hour : 10

In [63]:
print(df.head())

        Date   Time             Description   Type  Amount   Balance Mode  \
0 2024-01-01  03:11      AMAZON SELLER SVCS  debit  2462.0  678275.0  UPI
3 2024-01-01  14:07    UPI-AMAN-8934@OKAXIS  debit  1828.0 -748745.0  UPI
5 2024-01-01  14:48              BHIM ZEPTO  debit   625.0  677650.0  UPI
6 2024-01-01  14:50  UPI-UBER-2426@HDFCBANK  debit   148.0  677020.0  UPI
8 2024-02-01  05:18    POS SWIGGY BANGALORE  debit   537.0  676177.0  UPI

         Ref             Vendor           Category  Month  Hour
0  TXN190872             Amazon         E-commerce      1     3
3  TXN569226  Personal Transfer  Personal Transfer      1    14
5  TXN370902              Zepto     Quick Commerce      1    14
6  TXN546173               Uber          Transport      1    14
8  TXN293319             Swiggy      Food Delivery      2     5

In [64]:
print("debit_data" in globals())

True

In [65]:
# Calculate category-wise average amount
category_mean = debit_data.groupby("Category")["Amount"].transform("mean")
category_mean.head()

0    2801.230769
3    1300.000000
5     478.200000
6     310.476190
8     445.840909
Name: Amount, dtype: float64

In [66]:
# Calculate category-wise standard deviation
category_std = debit_data.groupby("Category")["Amount"].transform("std")
category_std.head()

0    2585.550688
3     753.758582
5     206.129840
6     119.501305
8     131.648041
Name: Amount, dtype: float64

In [67]:
# Calculate Z-Score
debit_data["Z_Score"] = (
    debit_data["Amount"] - category_mean
) / category_std
debit_data[["Amount", "Category", "Z_Score"]].head()

/tmp/ipykernel_2979/588509413.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  debit_data["Z_Score"] = (

   Amount           Category   Z_Score
0  2462.0         E-commerce -0.131203
3  1828.0  Personal Transfer  0.700490
5   625.0     Quick Commerce  0.712172
6   148.0          Transport -1.359619
8   537.0      Food Delivery  0.692445

In [68]:
# Identify unusual transactions
anomalies = debit_data[debit_data["Z_Score"] > 3]
print("Number of Anomalies :", len(anomalies))

Number of Anomalies : 1

In [69]:
# Display anomaly transactions
anomalies[
    [
        "Date",
        "Description",
        "Vendor",
        "Category",
        "Amount",
        "Z_Score"
    ]
]

         Date          Description  Vendor    Category   Amount  Z_Score
70 2024-09-01  UPI-MYNTRA@HDFCBANK  Myntra  E-commerce  10745.0  3.07237

In [70]:
# Sort anomalies by Z-Score
anomalies = anomalies.sort_values(
    by="Z_Score",
    ascending=False
)
anomalies.head(10)

,Date,Time,Description,Type,Amount,Balance,Mode,Ref,Vendor,Category,Month,Hour,Z_Score
70,2024-09-01,20:00,UPI-MYNTRA@HDFCBANK,debit,10745.0,-370896.0,UPI,TXN947220,Myntra,E-commerce,9,20,3.07237

In [71]:
# Display top anomaly
if len(anomalies) > 0:
    print("Highest Anomaly")
    print(anomalies.iloc[0])
else:
    print("No anomalies found.")

Highest Anomaly
Date           2024-09-01 00:00:00
Time                         20:00
Description    UPI-MYNTRA@HDFCBANK
Type                         debit
Amount                     10745.0
Balance                  -370896.0
Mode                           UPI
Ref                      TXN947220
Vendor                      Myntra
Category                E-commerce
Month                            9
Hour                            20
Z_Score                    3.07237
Name: 70, dtype: object

In [72]:
# Summary of anomalies
print("=" * 50)
print("ANOMALY DETECTION")
print("=" * 50)
print("Total Anomalies :", len(anomalies))
if len(anomalies) > 0:
    print()
    print(anomalies[
        [
            "Vendor",
            "Category",
            "Amount",
            "Z_Score"
        ]
    ].head())

==================================================
ANOMALY DETECTION
==================================================
Total Anomalies : 1

    Vendor    Category   Amount  Z_Score
70  Myntra  E-commerce  10745.0  3.07237

In [73]:
# Calculate total debit amount
total_debit = debit_data["Amount"].sum()
print("Total Debit :", round(total_debit, 2))

Total Debit : 205310.0

In [74]:
# Calculate spending percentage for each category
category_spending = debit_data.groupby("Category")["Amount"].sum()
category_percentage = (category_spending / total_debit) * 100
category_percentage = round(category_percentage, 2)
category_percentage

Category
Cafe                  1.41
Cash Withdrawal       1.46
E-commerce           17.74
Entertainment         1.15
Food Delivery         9.55
Fuel                  0.53
Groceries             3.74
Investments          31.41
Others                1.57
Personal Transfer     2.53
Quick Commerce        2.33
Rent                 17.53
Restaurants           2.72
Subscriptions         0.82
Transport             3.18
Utilities             1.79
Wallet                0.54
Name: Amount, dtype: float64

In [75]:
# Display category percentages
for category in category_percentage.index:
    print(category, ":", category_percentage[category], "%")

Cafe : 1.41 %
Cash Withdrawal : 1.46 %
E-commerce : 17.74 %
Entertainment : 1.15 %
Food Delivery : 9.55 %
Fuel : 0.53 %
Groceries : 3.74 %
Investments : 31.41 %
Others : 1.57 %
Personal Transfer : 2.53 %
Quick Commerce : 2.33 %
Rent : 17.53 %
Restaurants : 2.72 %
Subscriptions : 0.82 %
Transport : 3.18 %
Utilities : 1.79 %
Wallet : 0.54 %

In [76]:
# Create an empty list to store archetypes
archetypes = []

In [77]:
# Identify Foodie
if "Food Delivery" in category_percentage.index:
    if category_percentage["Food Delivery"] >= 20:
        archetypes.append("THE FOODIE")

In [78]:
# Identify Quick Commerce User
if "Quick Commerce" in category_percentage.index:
    if category_percentage["Quick Commerce"] >= 10:
        archetypes.append("THE QUICK COMMERCE USER")

In [79]:
# Identify Shopaholic
if "E-commerce" in category_percentage.index:
    if category_percentage["E-commerce"] >= 15:
        archetypes.append("THE SHOPAHOLIC")

In [80]:
# Identify Investor
if "Investments" in category_percentage.index:
    if category_percentage["Investments"] >= 10:
        archetypes.append("THE INVESTOR")

In [81]:
# Find late-night food delivery transactions
late_food = debit_data[
    (debit_data["Category"] == "Food Delivery") &
    (debit_data["Hour"] >= 21)
]
food_total = len(
    debit_data[
        debit_data["Category"] == "Food Delivery"
    ]
)
late_food_total = len(late_food)
print("Late Night Orders :", late_food_total)

Late Night Orders : 9

In [82]:
# Calculate late-night food percentage
if food_total > 0:
    late_food_percentage = (
        late_food_total / food_total
    ) * 100
else:
    late_food_percentage = 0
print("Late Night Food % :", round(late_food_percentage, 2))

Late Night Food % : 20.45

In [83]:
# Identify Late-Night Snacker
if late_food_percentage >= 50:
    archetypes.append("THE LATE-NIGHT SNACKER")

In [84]:
# Identify YOLO Spender
if net_savings < 0:
    archetypes.append("THE YOLO SPENDER")

In [85]:
# Display detected archetypes
print("=" * 50)
print("SPENDING ARCHETYPES")
print("=" * 50)
for item in archetypes:
    print(item)

==================================================
SPENDING ARCHETYPES
==================================================
THE SHOPAHOLIC
THE INVESTOR
THE YOLO SPENDER

In [86]:
# Count detected archetypes
print("Total Archetypes Detected :", len(archetypes))

Total Archetypes Detected : 3

In [87]:
# Display SpendDNA report header
print("=" * 60)
print(" " * 18 + "SPENDDNA REPORT")
print("=" * 60)

============================================================
                  SPENDDNA REPORT
============================================================

In [88]:
# Display spending overview
print("\nSPENDING OVERVIEW")
print("-" * 60)
print("Total Transactions :", total_transactions)
print("Total Credit       :", round(total_credit, 2))
print("Total Debit        :", round(total_debit, 2))
print("Net Savings        :", round(net_savings, 2))
print("Savings Rate       :", round(savings_rate, 2), "%")

SPENDING OVERVIEW
------------------------------------------------------------
Total Transactions : 143
Total Credit       : 170094.0
Total Debit        : 205310.0
Net Savings        : -35216.0
Savings Rate       : -20.7 %

In [89]:
# Display top spending categories
print("\nTOP SPENDING CATEGORIES")
print("-" * 60)
for category in top_categories.index:
    print(category, ":", round(top_categories[category], 2))

TOP SPENDING CATEGORIES
------------------------------------------------------------
Investments : 64496.0
E-commerce : 36416.0
Rent : 36000.0
Food Delivery : 19617.0
Groceries : 7672.0

In [90]:
# Display top vendors
print("\nTOP VENDORS")
print("-" * 60)
for vendor in top_vendors.index:
    print(vendor, ":", round(top_vendors[vendor], 2))

TOP VENDORS
------------------------------------------------------------
Zerodha : 60000.0
Rent : 36000.0
Myntra : 13629.0
Swiggy : 12638.0
Flipkart : 10041.0

In [91]:
# Display monthly spending
print("\nMONTHLY SPENDING")
print("-" * 60)
for month in monthly_spending.index:
    print("Month", month, ":", round(monthly_spending[month], 2))

MONTHLY SPENDING
------------------------------------------------------------
Month 1 : 14972.0
Month 2 : 6390.0
Month 3 : 26578.0
Month 4 : 5246.0
Month 5 : 21011.0
Month 6 : 9292.0
Month 7 : 23632.0
Month 8 : 41383.0
Month 9 : 14154.0
Month 10 : 5541.0
Month 11 : 6366.0
Month 12 : 30745.0

In [92]:
# Display spending archetypes
print("\nSPENDING ARCHETYPES")
print("-" * 60)
for item in archetypes:
    print(item)

SPENDING ARCHETYPES
------------------------------------------------------------
THE SHOPAHOLIC
THE INVESTOR
THE YOLO SPENDER

In [93]:
# Display anomaly summary
print("\nANOMALY SUMMARY")
print("-" * 60)
print("Total Anomalies :", len(anomalies))
if len(anomalies) > 0:
    print()
    print(anomalies[
        [
            "Vendor",
            "Category",
            "Amount"
        ]
    ].head())

ANOMALY SUMMARY
------------------------------------------------------------
Total Anomalies : 1

    Vendor    Category   Amount
70  Myntra  E-commerce  10745.0

## Project Insights

### Insight 1
The highest amount of spending was observed in the top spending category, indicating where most of the monthly expenses were concentrated.

### Insight 2
The monthly spending analysis showed noticeable variations across different months, helping identify periods of higher expenses.

### Insight 3
The anomaly detection highlighted unusually large transactions, which can be useful for identifying exceptional purchases or monitoring financial behavior.

## Project Reflection

This project helped me understand how transaction data can be cleaned, processed, and analyzed using Python, NumPy, and Pandas. I learned how to extract meaningful information from raw financial records, identify spending patterns, classify transactions into categories, and generate useful insights. It also improved my understanding of data cleaning, grouping, aggregation, and analytical thinking.

# Conclusion

The SpendDNA project successfully analyzed financial transactions by performing data cleaning, vendor extraction, category mapping, spending analysis, anomaly detection, and spending archetype identification. The final report provides a clear overview of financial behavior and demonstrates how Python can be used to solve real-world transaction analysis problems.